name: HDocBuild_Push
on:
  # Triggers the workflow on push requests
  push:
    paths-ignore:
      - '.github/**'
  
  # Triggers the workflow on pull request opened or reopened events
  pull_request_target:
    types: [opened, reopened]
    paths-ignore:
      - '.github/**'

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the relevant content - different for Push & Pull Request
      - name: Checkout For Push or Workflow Dispatch
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.inputs.branch }}
           fetch-depth: 0    
      - name: Checkout For Pull Request Target
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      # Setup NodeJS LTS (18 currently)
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install hdoc-tools globally
      - name: Install hdoc-tools
        run: npm install hdoc-tools -g
     
     # Run hdoc build against checked-out content
      - name: Perform Validation
        id: hdocbuild
        run: |
          if result=`hdoc build 2>&1`; then
              printf "Build Success!\n\n"
              printf "$result"
              exit 0
          else
            valout=$(echo "$result" | awk '/Validation Output/,0')
            printf "Build Failed!\n\n-----------------------\n"
            printf "$valout"
            exit 1
          fi
          
      # If build validation fails, and event trigger was a pull request  then close the pull request
      - name: Reject Pull Request
        if: failure() && github.event_name == 'pull_request_target'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "Your pull request has been rejected as build validation has failed. See the Perform Validation step of the build job for more information: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      
      # If build validation is successful, echo message
      - name: Build Success
        if: success()
        run: echo "::notice::Build validation passed successfully."
