name: HDoc_Validation
on:
  # Triggers the workflow on pull request opened or reopened events
  pull_request_target:
    types: [opened, reopened]

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Perform tests
        id: hdoc_build
        run: |
          npm install hdoc-tools -g
          hdoc build
          
      - name: Reject Pull Request
        if: failure()
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "Your pull request has been rejected as the hdoc build validation has failed."
          
      - name: Accept Pull Request
        if: success()
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
