name: HDocBuild_Push
on:
  # Triggers the workflow on push requests
  push:
    paths-ignore:
      - '.github/**'
  
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-shared-push-validation:
    uses: Hornbill-Docs/hdoc-library/.github/workflows/hdocbuild_shared_push.yml@f747d09f8486273eec1f4368bdb973db83b593e6
