name: HDocBuild_Push
on:
  # Triggers the workflow on push requests
  push:
    paths-ignore:
      - '.github/**'
  
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-shared-push-validation:
    uses: Hornbill-Docs/hdoc-library/.github/workflows/hdocbuild_shared_push.yml@8c43ee2385d364537ecee64b9860869efc73766c
